###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: helpdesk20-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: helpdesk20-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: helpdesk20-postgres
      working_dir: /application
      volumes:
        - .:/application:cached
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=z123b15
        - POSTGRES_DB=helpdesk

    webserver:
      image: nginx:alpine
      container_name: helpdesk20-webserver
      working_dir: /application
      volumes:
          - .:/application:cached
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: helpdesk20-php-fpm
      working_dir: /application
      environment:
        - DATABASE_URL=pgsql://postgres:z123b15@postgres/helpdesk
      volumes:
        - .:/application:cached
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini:ro
